### PR TITLE
Feature/add node build 10.12

### PR DESCRIPTION
**Pull request by jayhof**
This PR adds a new node build image (version 10.12) and explains the repos purpose in the readme.

### CODE REVIEW

**Comment by jayhof** [comment]
In the future it might be easier to version these images if we do split them up into separate repositories.

**Review by lightblader — APPROVED** [review]
Looks good. Have you set up the new tag for building it on dockerhub? :)

**Comment by jayhof** [comment]
@lightblader yeah docker hub is ready for this change

**Review by BastianHofmann — APPROVED** [review]

**Comment by BastianHofmann** [comment]
@jayhof how would you like to split up the images into separate repositories?

**Comment by BastianHofmann** [comment]
@jayhof I think the official images use one repository per image, with multiple tags per repository.

**Comment by jayhof** [comment]
@BastianHofmann right, one repo per image with tags for versions.

**Pull request merged**
